### ISSUE TITLE
Did you planned to support the projections?

### ISSUE THREAD

**Issue by ikasymov** [pyeventsourcing/esdbclient#10]

**Comment by johnbywater** [comment]
Hi @ikasymov!

Yes this is something we are planning to support. It wasn't included for the forthcoming v1.0 release, but it will be supported soon in a subsequent release. I've mentioned your question to the EventStoreDB people I'm working with, so hopefully it will become a priority now. :-)

**Comment by ikasymov** [comment]
@johnbywater Creating the new projections. If I understand correctly, we can read system projections already.

**Comment by johnbywater** [comment]
Alright, thanks for letting me know. Yes we can read system projections already. Creating new projections is forthcoming.

**Comment by ikasymov** [comment]
@johnbywater Stop, I can't read the custom projection result by the read_stream function. I got the error:
`esdbclient.exceptions.NotFound: Stream 'tester_projection' not found
`
What do I need to do to read the result of the simple projection like this?
```
fromStream('stock_1')
.when({
    $init: function(){
        return {
            count: 0
        }
    },
    $any: function(s,e){
        s.count += 1;
    }
})
```

**Comment by johnbywater** [comment]
@ikasymov I've implemented the Projections API.
https://github.com/pyeventsourcing/esdbclient?tab=readme-ov-file#projections

Published as pre-release v1.1b1:
https://pypi.org/project/esdbclient/1.1b1/

**Comment by johnbywater** [comment]
> What do I need to do to read the result of the simple projection like this?

You need to call the `get_projection_state()` method - see the docs :-)

**Comment by ikasymov** [comment]
It's great news. Thanks so much!

**Comment by johnbywater** [comment]
Hey @ikasymov just wanted to let you know that stable version 1.1 was just published, which has support for projections amongst other new things.

**Comment by ikasymov** [comment]
awesome news! Thanks!
