### ISSUE TITLE
Persistent Subscriptions and resolve_links=True

### ISSUE THREAD

**Issue by realtonyyoung** [pyeventsourcing/esdbclient#13]
I've noticed that catchup subscriptions support resolve_links=True, so we can listen to event type projection streams, and read the events from them

Persistent subscriptions, however, do not have this capability, and in 1.0.2 will return a link instead of the resolved event

Please add the resolve_links option to the read_subscription_to_stream method

NOTE: .NET client supports this behaviour so the server should support it

**Comment by johnbywater** [comment]
Thanks @realtonyyoung! I will do this now. Also the same thing on the `read_all()` method. It's not implemented but could/should be. Just give me a few minutes....

**Comment by johnbywater** [comment]
All the methods which could have `resolve_links` do have now:

- read_stream()
- get_stream()
- subscribe_to_stream()
- create_subscription_to_stream()
- update_subscription_to_stream()
- read_all()
- subscribe_to_all()
- create_subscription_to_all()
- update_subscription_to_all()

The docs have been updated accordingly.

Please update to v1.0.3 and let me know if that's what you were looking for?

https://pypi.org/project/esdbclient/1.0.3/

Thanks again for raising the issue. Hope that helps!

**Comment by w1am** [comment]
Thank you, @johnbywater. Could you please update the samples for [read-all](https://github.com/pyeventsourcing/esdbclient/blob/63b32c6ceeeb09653f331929580c0ec19fb32f1d/samples/reading_events.py#L153C27-L153C27) and [update-persistent-subscription](https://github.com/pyeventsourcing/esdbclient/blob/63b32c6ceeeb09653f331929580c0ec19fb32f1d/samples/persistent_subscriptions.py#L164) to include the `resolve_links` method, ensuring they appear correctly on the website?

**Comment by johnbywater** [comment]
I've done that William. I made quite a few changes to the samples files.

**Comment by johnbywater** [comment]
Actually, these two have `resolve_links`:

```
events = client.read_all(
    commit_position=0,
    limit=100,
    resolve_links=True,
)
```

```
subscription = client.subscribe_to_stream(
    stream_name="$et-MyEventType",
    stream_position=0,
    resolve_links=True,
)
```

I'm just pushing this one now:

```
client.update_subscription_to_stream(
    stream_name=stream_name,
    group_name=group_name,
    resolve_links=True,
)
```

**Comment by johnbywater** [comment]
I don't know what reference you are using when pulling these snippets into the website? Are you using the 1.0 branch? Or a tag? I mean, do I need to tag these changes?

**Comment by w1am** [comment]
@johnbywater  No need to tag it. It will pull the latest changes from the 1.0 branch.

**Comment by johnbywater** [comment]
[offtopic here, but...]

I've actually made quite a lot of changes to the samples. I hope you like what I've done. I was just trying to rationalise them after seeing how they appear within the surrounding text. Also, for example, reordering the snippets in the Python files so they have the same order as they appear on the website (for maintainability).

The things that took me the most time were the sections that read from a subscription. Making something that works in the same way in each example, is readable and instructive, and actually works as code. It's kind of hard to match the slightly deranged surrounding prose. But I tried to do my best. What do you think?

Catch-up subscription to stream:

```
last_stream_position = 0

while True:
    subscription = client.subscribe_to_stream(
        stream_name=stream_name,
        stream_position=last_stream_position,
    )
    try:
        for event in subscription:
            # remember stream position
            last_stream_position = event.stream_position

            # record stream position
            handle_event(event)

    except AbortedByServer:
        # resubscribe from last known position
        continue
```

Catch-up subscription to all with server-side filtering and checkpoints:

```
# get last recorded commit position
last_commit_position = 0

while True:
    subscription = client.subscribe_to_all(
        commit_position=last_commit_position,
        filter_by_stream_name=True,
        filter_include=["account.*", "savings.*"],
        include_checkpoints=True,
    )
    try:
        for received in subscription:
            last_commit_position = received.commit_position

            # checkpoints are like events but only have a commit position
            if isinstance(received, Checkpoint):
                print("We got a checkpoint!")
            else:
                print("We got an event!")

            # record commit position
            handle_event(received)

    except AbortedByServer:
        # resubscribe from last known position
        continue
```

Reading a persistent subscription (the final "manual acks" section):

```
while True:
    subscription = client.read_subscription_to_stream(
        group_name=group_name,
        stream_name=stream_name,
    )
    try:
        for event in subscription:
            try:
                handle_event(event)
            except Exception:
                if event.retry_count < 5:
                    subscription.nack(
                        event_id=event.id, action="retry"
                    )
                else:
                    subscription.nack(
                        event_id=event.id, action="park"
                    )
            else:
                subscription.ack(event_id=event.id)

    except AbortedByServer:
        # reconnect
        continue
```

The trick is that the `handle_event()` method calls `subscription.stop()` which terminates the iterator, and then there's a `break` immediately after the try/except block after the "end" tag so it's hidden from the website. So each snippet runs through once and then exits. But they look like they will run forever despite "dropped subscription" unless another type of exception is raised, which is kind of what you want.

**Comment by ikasymov** [comment]
@johnbywater 
Please do not forget to also add the link_event_id attribute to RecordedEvent. It will be necessary when, for example, we want to do ack() the linked stream in a Persistent stream.

**Comment by johnbywater** [comment]
I just edited the samples and the comment above to have:

```
    except ConsumerTooSlow:
        # subscription was dropped
        continue
```

I will stop making changes now :) if you would be so kind as to pull these latest changes into the website so we can review it all again, that would be super great!

**Comment by ikasymov** [comment]
@johnbywater 
I just want to clarify the my above comment and:
   ```
 client = get_event_store_client()
    client.create_subscription_to_stream(
        group_name="cooking",
        stream_name=f"$ce-acquired_orders",
        resolve_links=True,
    )
    subscription = client.read_subscription_to_stream(
        group_name="cooking",
        stream_name=f"$ce-acquired_orders",
    )

    for event in subscription:
        subscription.ack(event_id=event.id)
```

This code doesn't work because we can't ack() the linked streams.

**Comment by johnbywater** [comment]
@ikasymov thanks for the suggestion. I will try to do this. I'm still learning about links. I don't understand this aspect very well. I was talking about it with Yves this morning. He said he will send me a document that explains everything. Then I will review all this and try to fix what's lacking.

In the meantime, if you would like to explain a bit more, that would be very helpful. For example, from where does the link ID come from when the link events have, and also haven't, been resolved? I was puzzling over this for several hours yesterday.

**Comment by johnbywater** [comment]
> I just want to clarify the my above comment ....

Thanks @ikasymov! What should be the value of `event.linked_event_id`?

There's `ReadResp.event.link` which is a `ReadResp.RecordedEvent`. And `ReadResp.RecordedEvent` has an `id` which is a `UUID`. Do I used the ID from the `link` recorded event?

**Comment by ikasymov** [comment]
@johnbywater 
I think we should use the `ReadResp.event.link.id` as the linked_event_id.
If `resolve_links=False` then `linked_event_id` value will be None.

I'm not very good at this, but to me, it looks like this. 

I have a good idea:
What if we completely return the link attribute as a `RecordedEvent.link: RecordedEvent `if it is present, if not, then do not return it. In this situation, we will not be bound to the `resolve_links` field.

**Comment by ikasymov** [comment]
I think `RecoredEvent` dataclass should be like this:
```
@dataclass(frozen=True)
class RecordedEvent:
    ...
    link: 'RecordedEvent'
```

**Comment by ikasymov** [comment]
It will be good because my own project is blocked right now by this problem. Thanks very much!! @johnbywater

**Comment by johnbywater** [comment]
@ikasymov what did you mean by "we will not be bound to the resolve_links field"?

**Comment by ikasymov** [comment]
@johnbywater 
I mean we don't need to check the resolve_links flag to create the link attribute. It is enough for us to understand that GRPC returns the link attribute, if it returns a `link` then create it.

**Comment by johnbywater** [comment]
@ikasymov I implemented your suggestion in 0b63dec5850d83ed96389294bd24106d03a70481

> The `link` attribute is an optional `RecordedEvent` that carries information about "links". This allows link events to be acknowledged or negatively acknowledged when using persistence subscriptions with the `resolve_links` argument set to `True`.

https://pypi.org/project/esdbclient/#recorded-events

Please update to version 1.0.6 and let us know what you think?

**Comment by johnbywater** [comment]
> I mean we don't need to check the resolve_links flag to create the link attribute. It is enough for us to understand that GRPC returns the link attribute, if it returns a link then create it.

Then create what? :-) I'm sorry I still don't understand! I don't understand what "link" contains. The only thing I understand is that if you call `read_all()` with `resolve_links=True` and `filter_exclude=[]` then you get several instances of all of your events, because of the system projections. That's actually all I understand right now. I need to understand this better.

**Comment by johnbywater** [comment]
@ikasymov I need to go out soon, so if v1.0.6 doesn't unblock your project, we will need to resume tomorrow. Thanks for your contributions today!

**Comment by ikasymov** [comment]
@johnbywater I mean about that https://github.com/pyeventsourcing/esdbclient/commit/0b63dec5850d83ed96389294bd24106d03a70481#diff-40f956c8956a4a333885159e00886da46aa099bd929aa9ced8a950be94f20a6bR163

And your implementation looks like how I expected. Thanks so much!

**Comment by johnbywater** [comment]
> I mean about that

Oh right yes! I understand. I thought you were talking about your project. It's nice that we don't need somehow to pass the `resolve_links` value into the function that returns `RecordedEvent`. It's not available when reading a persistent subscription, unless the subscription info is retrieved from the server.

> And your implementation looks like how I expected. Thanks so much!

Great to hear! Let us know if your project is unblocked now? :)

**Comment by ikasymov** [comment]
> Great to hear! Let us know if your project is unblocked now? :)

Yep! Thanks!

**Comment by johnbywater** [comment]
Fabulous.
