### ISSUE TITLE
Add support for caught up and fell behind message

### ISSUE THREAD

**Issue by w1am** [pyeventsourcing/esdbclient#19]
This year, work was done on the server to support 'caught up' and 'fell behind' notifications for catch-up subscriptions. It would be great if this client supported those messages.

**Comment by johnbywater** [comment]
Thanks @w1am!

**Comment by johnbywater** [comment]
This was done in 90150fb9d610eade12c95da83949a3c3d4aee125 and released in v1.0.23.
