### ISSUE TITLE
RecordedEvent missing timestamp

### ISSUE THREAD

**Issue by cdavernas** [pyeventsourcing/esdbclient#22]
RecordedEvent are missing timestamp, which is however supplied by event store (cfr. `createdAt`) and which is usefull when describing a given stream (lfirst event at/last event at).

Am I missing something?

**Comment by johnbywater** [comment]
If you update to v1.0.20 there is a new attribute `recorded_at`. Hope that helps?

**Comment by cdavernas** [comment]
Wonderful! Many thanks!
