### ISSUE TITLE
Missing release and commit tags for pypi published version?

### ISSUE THREAD

**Issue by goznauk** [pyeventsourcing/esdbclient#4]
It's quite minor issue, but I think adding this for published version is useful.

[v0.5](https://github.com/pyeventsourcing/esdbclient/commit/53a7f2aa8c59bdc6454d8b8d36a9c9ef82c98755)
[v0.6](https://github.com/pyeventsourcing/esdbclient/commit/d0e72c8cb7a16f74fb497759614aa21c09578f92)

Would you mind adding some tags for commits for these versions?
Thanks.

**Comment by johnbywater** [comment]
Good point @goznauk! Yes I will do this, and will also do this for future releases.

**Comment by johnbywater** [comment]
I just added the tags: https://github.com/pyeventsourcing/esdbclient/tags
