### ISSUE TITLE
How to read the EventType stream?

### ISSUE THREAD

**Issue by drozzy** [pyeventsourcing/esdbclient#6]
I know in event store you can subscribe to $et-EventType stream to get all those events.

However, when I try to do that with esdbclient:
```python
stream_name = "$et-EventType"
    events = client.get_stream(
        stream_name=stream_name
    )
    event_types = []
    for event in events:
        print(event)
        print(event.data)
```

I only get the strange binary string with a `0@uuid` in it. I believe it is a link to the event, but I'm not sure how to get the actual event body:

```
RecordedEvent(type='$>', data=b'0@90a1af0f-f218-443e-8805-f2a419d78833', 
metadata=b'{"$v":"4:-1:1:4","$c":21867,"$p":21867,"$causedBy":"8e8c01d8-7819-4b7e-a891-d88a5cf6a9eb"}', 
content_type='application/octet-stream', id=UUID('ca25115c-fd64-4216-8361-132101384c00'), 
stream_name='$et-EventType', stream_position=0, commit_position=22961, retry_count=None)
```

**Comment by johnbywater** [comment]
Hi @drozzy, thanks for raising the issue and sorry for the delay - I was having an extended summer break.

I'm not sure what the convention "$et-EventType" is, but will look into this.

At the moment links to events aren't supported by the client. I'm working under guidance from the Event Store DB team, and this aspect simply hasn't been "in scope" for v1.  There's a field in the protobuf message which could be resolved, but at the moment it isn't - at the moment, it's just ignored by the client.

I will ask the Event Store DB team about this. I'm sure it will be supported soon.

Again, thanks for raising the issue, and sorry for the delay in replying. I'm back now!

**Comment by johnbywater** [comment]
Hi @drozzy,

I added a `resolve_links` argument to the `get_stream()` and `read_stream()` methods.

Please can you update to version 0.19 or 1.0b4 and try again, with the additional argument `resolve_links=True`?

https://pypi.org/project/esdbclient/0.19/
https://pypi.org/project/esdbclient/1.0b4/

> The `read_stream()` and `get_stream()` methods also have five optional arguments, `stream_position`, `backwards`, `resolve_links`, `limit`, and `timeout`.
>
> The optional `resolve_links` argument is a Python `bool`. The default value of `resolve_links` is `False`, which means any event links will not be resolved, so that the events that are returned may represent event links. If `resolve_links` is `True`, any event links will be resolved, so that the linked events will be returned instead of the event links.

The `subscribe_to_stream()` method also now supports this argument. There's a test in the test suite which demonstrates this feature. I noticed the result is the same as reading all events with the `filter_include` argument set to the event type.

Please let me know if this `resolve_links=True` argument gives you what you were looking for?
